### ISSUE TITLE
Support Pasting

### ISSUE THREAD

**Issue by darkfrog26** [cloverhearts/quilljs-markdown#23]
If I paste a block of Markdown it does not automatically format it at all.

**Comment by cloverhearts** [comment]
Thank you for your nice idea!
I will check it soon.

**Comment by darkfrog26** [comment]
Wouldn't this be considered a bug? I would think the operation of an editor is such that pasting and typing should have identical parsing, right?

**Comment by cloverhearts** [comment]
In my opinion, that is not a bug.
Because I did not consider the specification for paste in this module.
This module started out as a shortcut for Markdown syntax.
So, actually, this plugin doesn't render the markdown syntax,

It just calls the syntax highlighting feature of the Quilljs module. (eg, toBold, toStyle, toHeader...)

Currently, in Quilljs's plugin hierarchy, it should be Quilljs, not the plugin, that renders the body.
However, currently, the rendering demands for Markdown have increased.

In particular, I also agree with the need for paste.
This will be implemented as soon as.

**Comment by cloverhearts** [comment]
Work in progress at #24
